### ISSUE TITLE
System.ArgumentException: Requested value 'Failed' was not found.

### ISSUE THREAD

**Issue by karolsws2** [recurly/recurly-client-net#156]
Recurly resturns subscription with status "Failed" which is not presend in SeubscriptionStatus Enum

Subscription was created with startDate set to future, this subscription was then cancelled

then this call results with error:
account.GetSubscriptions(Subscription.SubscriptionState.All);

```
System.ArgumentException: Requested value 'Failed' was not found.
   at System.Enum.EnumResult.SetFailure(ParseFailureKind failure, String failureMessageID, Object failureMessageFormatArgument)
   at System.Enum.TryParseEnum(Type enumType, String value, Boolean ignoreCase, EnumResult& parseResult)
   at System.Enum.Parse(Type enumType, String value, Boolean ignoreCase)
   at Recurly.StringExtensions.ParseAsEnum[T](String source)
   at Recurly.Subscription.ReadXml(XmlTextReader reader)
   at Recurly.SubscriptionList.ReadXml(XmlTextReader reader)
   at Recurly.Client.ReadWebResponse(HttpWebResponse response, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate responseDelegate)
   at Recurly.Client.PerformRequest(HttpRequestMethod method, String urlPath, WriteXmlDelegate writeXmlDelegate, ReadXmlDelegate readXmlDelegate, ReadXmlListDelegate readXmlListDelegate, ReadResponseDelegate reseponseDelegate)
   at Recurly.RecurlyList`1.GetItems()
   at Recurly.Account.GetSubscriptions(SubscriptionState state)
   at BusinessLogic.RecurlyIntegration.RecurlyIntegrationService.GetAccountDetails(String site, Boolean withSubscirptions, Boolean withInvoicesAndTransactions) in C:\Users\admin\Documents\Visual Studio 2013\Projects\Qalculator\BusinessLogic\RecurlyIntegration\RecurlyIntegrationService.cs:line 79
   at Client.Controllers.AccountController.<GetSite>d__36.MoveNext() in C:\Users\admin\Documents\Visual Studio 2013\Projects\Qalculator\Prototyping\Controllers\AccountController.cs:line 1078
--- End of stack trace from previous location where exception was thrown ---
   at System.Runtime.CompilerServices.TaskAwaiter.ThrowForNonSuccess(Task task)
   at System.Runtime.CompilerServices.TaskAwaiter.HandleNonSuccessAndDebuggerNotification(Task task)
   at System.Web.Mvc.Async.TaskAsyncActionDescriptor.EndExecute(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass37.<BeginInvokeAsynchronousActionMethod>b__36(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethod(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3d()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.AsyncInvocationWithFilters.<>c__DisplayClass46.<InvokeActionMethodFilterAsynchronouslyRecursive>b__3f()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.EndInvokeActionMethodWithFilters(IAsyncResult asyncResult)
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<>c__DisplayClass2b.<BeginInvokeAction>b__1c()
   at System.Web.Mvc.Async.AsyncControllerActionInvoker.<>c__DisplayClass21.<BeginInvokeAction>b__1e(IAsyncResult asyncResult)
```

**Comment by bhelx** [comment]
I have a PR going to address this here: https://github.com/recurly/recurly-client-net/pull/177

Let me know if that works for you

**Comment by bhelx** [comment]
Closed with https://github.com/recurly/recurly-client-net/pull/177
