### ISSUE TITLE
Data at the root level is invalid. Line 1, position 1.

### ISSUE THREAD

**Issue by lsuminh** [recurly/recurly-client-net#829]
**Describe the bug**

Call Get Subscription return Error Data at the root level is invalid. Line 1, position 1.
Just happed one or two times in day.

**To Reproduce**

Steps to reproduce the behavior.

Exception for eventId 01000000-bea1-6aef-abc7-08dc63cda49d: Recurly.RecurlyError: Data at the root level is invalid. Line 1, position 1.
   at Recurly.BaseClient.HandleResponse(IRestResponse resp)
   at Recurly.BaseClient.<>c__DisplayClass18_0`1.<MakeRequestAsync>b__0(Task`1 t)
   at System.Threading.Tasks.ContinuationResultTaskFromResultTask`2.InnerInvoke()
   at System.Threading.ExecutionContext.RunFromThreadPoolDispatchLoop(Thread threadPoolThread, ExecutionContext executionContext, ContextCallback callback, Object state)

**Expected behavior**

Return a valid response object Subscription or Valid Recurly Error 

**Your Environment**

- Which version of this library are you using?
Version 4.32.1
- Which version of the language are you using?
.NET Core

**Comment by douglasmiller** [comment]
@lsuminh, thank you for reaching out. This was likely due to a temporary issue with API responses. This issue should be resolved, but please reach out if you experience more issues.
